### ISSUE TITLE
Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises

### ISSUE THREAD

**Issue by iftahnaf** [abichinger/semantic-release-pypi-example#2]
Hi,

In my `release.yml` I have the following configuration:

```yaml
name: Release

on: 
  push:
    branches: 
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/github @semantic-release/commit-analyzer @semantic-release/git @semantic-release/release-notes-generator semantic-release-pypi
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install setuptools
        run: python -m pip install --upgrade setuptools wheel twine
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_ACCESS_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: npx semantic-release
```

When merge PR, I have the following action error:

```
Run npx semantic-release
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_UNKNOWN_BUILTIN_MODULE]: No such built-in module: node:timers/promises
    at new NodeError (internal/errors.js:322:7)
    at Loader.builtinStrategy (internal/modules/esm/translators.js:28[9](https://github.com/iftahnaf/pyvectorguidance/actions/runs/6302935502/job/17111127252#step:7:10):[11](https://github.com/iftahnaf/pyvectorguidance/actions/runs/6302935502/job/17111127252#step:7:12))
    at new ModuleJob (internal/modules/esm/module_job.js:63:26)
    at Loader.getModuleJob (internal/modules/esm/loader.js:258:11)
    at async ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:78:[21](https://github.com/iftahnaf/pyvectorguidance/actions/runs/6302935502/job/17111127252#step:7:22))
    at async Promise.all (index 1)
    at async link (internal/modules/esm/module_job.js:83:9) {
  code: 'ERR_UNKNOWN_BUILTIN_MODULE'
}
Error: Process completed with exit code 1.
```

Any help would be much appreciated.

**Comment by abichinger** [comment]
Hey,

have you tried upgrading Node?
**semantic-release** requires Node version 18.0.0 or higher. ([Node version requirement](https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-version.md#node-version-requirement))

Node configuration:
```yaml
- uses: actions/setup-node@v3
  with:
    node-version: 18
```

**Update**
I upgraded the Node version in the release workflow of this example and can confirm that it solved the problem.
